### ISSUE TITLE
Custom cursor does not follow when using the scroll wheel

### ISSUE THREAD

**Issue by Miguelklappes** [LuXDAmore/vue-cursor-fx#9]
**Describe the bug**
If you leave the mouse static while you are scrolling down the page, the cursor will not follow the movement until you move it again.

**To Reproduce**
1- Scroll without moving the custom cursor
2- See how it stops and comes back again after movement (with the mouse, not the scroll wheel)

**Expected behavior**
Make the custom cursor follow the default at all times (when enabled).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Mozilla Firefox Developer Edition
 - Version: 89

**Comment by LuXDAmore** [comment]
Hi @Miguelklappes 😄 


Thank You for this issue, but i think it's something normal because I'm tracking the mouse-move and not the on-scroll events..

And i think it became a little bit complicated to do that.

Usually is the default behavior, if you scroll with the mouse hover something, the hover still keep in the previous element.

But if You want to try to make a PR with this enhancement, I'm happy to check and review it!


Have a nice day! 😸
